---
title: "Class5_Grader"
author: "Oren"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
score = 0
library(readxl)
library(quantmod)
students = list.files("Students/")

students_files = paste("Students", students, sep = "/")
# students = data.frame(students)
# students$score = 0
```


``` {r }
score = 0
grading = 19
file.edit(students_files[grading])
source(students_files[grading])
# load(students_files[1])
```


```{r qMatMult1}
ptsQ1 = 0
vec = matrix(data = 1:3,nrow = 1,ncol = 3)
mat = matrix(data = c(1,4,7),nrow = 3,ncol = 1)

x = MatMult2(vec,mat)

functionText = capture.output(MatMult2)

if (x[1] == 30){
  ptsQ1 = 1
  if(length(grep("for",functionText))>1){
    cat("Only 1 'for' loop allowed!")
    ptsQ1 = ptsQ1 -.5
  }
  if(length(grep("%*%",functionText))>0){
    cat("No Cheating :)")
    ptsQ1 = ptsQ1 -.5
  }
}
score = score + ptsQ1

```

```{r qMatMult1}
ptsQ2 = 0
vec = matrix(data = 1:3,nrow = 1,ncol = 3)
mat = matrix(data = 1:9,nrow = 3,ncol = 3,byrow = T)

x = MatMult1(vec,mat)
x[1] == 30 & x[2] == 36 & x[3] == 42

functionText = capture.output(MatMult1)

if (x[1] == 30 & x[2] == 36 & x[3] == 42){
  ptsQ2 = 1
  if(length(grep("for",functionText))>1){
    cat("Only 1 'for' loop allowed!")
    ptsQ2 = ptsQ2 -.5
  }
  if(length(grep("%*%",functionText))>0){
    cat("No Cheating :)")
    ptsQ2 = ptsQ2 -.5
  }
}
score = score + ptsQ2
```


```{r qTMat1}
ptsQ3 = 0
rLast = rep(c('A','B','C'),c(3,4,3))
rNow  = rep(c('A','B','C'),c(5,0,5))



out = TMAT1(rLast,rNow)
answer = c(1,.5,0,0,0,0,0,.5,1)
dim(answer) = c(3,3)
all.equal(out,answer)
ptsQ3 = 0
if (all.equal(out,answer) == TRUE){
  ptsQ3 = 1
}

score = score + ptsQ3
```



```{r qTMat2}
ptsQ4 = 0
vec = matrix(data = c(20,30,10),nrow = 1,ncol = 3)
mat = c(1,.5,0,0,0,0,0,.5,1)
dim(mat) = c(3,3)

x = MatMult(vec,mat)
x[1] == 35 & x[2] == 0 & x[3] == 25

functionText = capture.output(MatMult)
if(length(grep("for",functionText))!=1){
  cat("Only 1 'for' loop allowed!")
}


if (x[1] == 35 & x[2] == 0 & x[3] == 25){
  ptsQ4 = 1
if(length(grep("for",functionText))!=1){
  cat("Only 1 'for' loop allowed!")
    ptsQ4 = ptsQ4 -.5
  }

}

score = score + ptsQ4
```


```{r qBondPrice}
ptsQ5 = 0
y = 0.03
face = 2000000
couponRate = 0.04
m = 10
ppy = 2

functionText = capture.output(getBondPrice)
ptsQ5 = 0
x = getBondPrice(y, face, couponRate, m,  1)
if (round(x) == 2170604){
  ptsQ5 = .5
  if(length(grep("for",functionText))){
  cat("No 'for' loops allowed!")
    ptsQ5 = ptsQ5 - .5
  }
}

x = getBondPrice(y, face, couponRate, m,  2)
if (round(x) == 2171686){
  ptsQ5 = ptsQ5 + .5
  if(length(grep("for",functionText))){
  cat("No 'for' loops allowed!")
    ptsQ5 = ptsQ5 - .5
  }
}

score = score + ptsQ5
```


```{r qBondDuration}
ptsQ6 = 0
y = 0.03
face = 2000000
couponRate = 0.04
m = 10

x = getBondDuration(y, face, couponRate, m)
functionText = capture.output(getBondDuration)


if (round(x,2) == 8.51){
  ptsQ6 = 1
  if(length(grep("for",functionText))){
  cat("No 'for' loops allowed!")
    ptsQ6 = ptsQ6 - 1
  }
}

score = score + ptsQ6
```


```{r qBondPriceFromCurve}
ptsQ7 = 0
YC <- read_excel("C4RM_Class5.xlsx",
sheet = "qBondPriceFromCurve", range = "G3:G12",
col_names = FALSE)

YC = as.matrix(YC)
y = .03
face = 2000000
couponRate = 0.04
m = 10
ptsQ7 = 0
x1 = getBondPriceYC(y, face, couponRate, m)
if (round(x1) == 2170604){
  ptsQ7 = ptsQ7 + .5
}

x2 = getBondPriceYC(YC, face, couponRate, m)
if (round(x2) ==  1267138){
  ptsQ7 = ptsQ7 + .5
}

functionText = capture.output(getBondPriceYC)
if(
  length(grep("if",functionText))==0 &
  round(x1) == 2170604 &
  round(x2) ==  1267138
  ){
  cat("Congraulations!\n")
  cat("You answered without using 'if'.\n")
  cat("You get an extra point in this assignment.")
  ptsQ7 = ptsQ7 + 1
}
score = score + ptsQ7
```



```{r qConditioning}
ptsQ8 = 0
x = FizzBuzz(40,45)
ptsQ8 = 0
if (x[1] == "buzz" & x[2] == "41" & x[6] == "fizzbuzz"){
  ptsQ8 = 2
}
if (x[1] == "Buzz" & x[2] == "41" & x[6] == "FizzBuzz"){
  ptsQ8 = 2
}
score = score + ptsQ8
```


```{r qGetReturns}
ptsQ9 = 1
# NEED CODE HERE
score = score + ptsQ9

```


```{r}
# students[grading,2]  = score
students[grading]
score
```

